name: 3co
favicon: null
layout_spectrum: 0.8584419623948634
typography_spectrum: 0.6596395371016115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.49940906115807593
  lightness: 0.4519534909632057
  saturation: 0.7972199914511293
  rhythmicContrast: 0.8331382235046476
purpose: []
